### ISSUE TITLE
Vertical layout for fzf windows when jj-fzf too narrow

### ISSUE THREAD

**Issue by niveK77pur** [tim-janik/jj-fzf#10]
Hello! First off, thank you for this amazing tool! Using fzf makes for such a sweet interaction with jj.

I do have an issue however, where jj-fzf's window is nearly unusable when my terminal window is too narrow. And this happens quite a lot to me, because I often have 2 windows side by side. Below is a screenshot of what jj-fzf looks like.

![Image](https://github.com/user-attachments/assets/73efa061-5531-4f61-bc68-b95611a7c3c9)

You can see that the log view on the left shows practically nothing of relevance anymore. The right view also suffers from line wraps making it clunky to see what is even happening.

I haven't looked at the implementation for this tool, but fzf by itself is definitely able to automatically rearrange the query window and the preview window in a horizontal and vertical manner depending on the available space, by specifying `--layout flex` option (if I am not mistaken now).

Would it be possible to conceive something similar for jj-fzf? In this case, the log view would be at the top, and the preview window at the bottom (possibly even able to hide the preview if there really is not enough space), allowing for more horizontal space to display more relevant information in both views.

**Comment by tim-janik** [comment]
> Would it be possible to conceive something similar for jj-fzf? In this case, the log view would be at the top, and the preview window at the bottom (possibly even able to hide the preview if there really is not enough space), allowing for more horizontal space to display more relevant information in both views.

There are two things you can currently do to adjust the layout:
- Alt+H to hide/show the help section
- F11 to toggle the preview between vertical/horizontal layout

Fzf would allow a lot more configurations to toggle between, but more than two or three layouts to toggle between with F11 is likely going to be confusing for users...

**Comment by niveK77pur** [comment]
Thank you for the F11 hint! Is it documented anywhere? At least I cannot find it in the help menu that appears when pressing ctrl+h. That said, I think F11 as it is now is perfect then and addressed my use case!

Just out of curiosity: Is there any way to forward options to fzf behind the scenes? Such as `--layout flex` or other if I desire more control?

However, Alt+H doesn't seem to be working properly for me. I am using Fish if that makes any difference. Basically, pressing Alt+H moves the prompt to the bottom of the window, but the help section is still there (at least after something causes a UI refresh). However, the inverse doesn't make the help section appear anymore?

**Comment by tim-janik** [comment]
> Thank you for the F11 hint! Is it documented anywhere? At least I cannot find it in the help menu that appears when pressing ctrl+h. That said, I think F11 as it is now is perfect then and addressed my use case!

Right, I have fixed this in e3c578f1ce066c52795d9ef4fe134eee1c0471db.

> Just out of curiosity: Is there any way to forward options to fzf behind the scenes? Such as `--layout flex` or other if I desire more control?

AFAIK, fzf has no `--layout flex` option.
And currently some parts (e.g. the help column calculation) are basd on a specific layout.
A few changes are pending past the next release, so if you have specific layout suggestions, that could be considered.

> However, Alt+H doesn't seem to be working properly for me. I am using Fish if that makes any difference. Basically, pressing Alt+H moves the prompt to the bottom of the window, but the help section is still there (at least after something causes a UI refresh). However, the inverse doesn't make the help section appear anymore?

Not sure what you are seeing. I just now that some terminals need a config setting enabled to pass through all alt keys, e.g. Alt+H. Maybe Alt+H changes the query filter instead if you can still see the help text?

**Comment by niveK77pur** [comment]
> I just now that some terminals need a config setting enabled to pass through all alt keys

~~Actually, this might be the problem, thank you. I am using ghostty, and there has been one instance where a key combination did not get passed through.~~ I observe the same behaviour in Konsole, if that's anything to go by.

I have attached a screenshot this time around to make it clearer. It seems to move the prompt to the bottom of the window but leaves the original help section visible above it, other than that visual change, nothing else seems to change:

<img width="1083" height="609" alt="Image" src="https://github.com/user-attachments/assets/aa4dadb8-8d5c-4c8c-a527-02e91f5afd14" />

**Comment by tim-janik** [comment]
> I have attached a screenshot this time around to make it clearer. It seems to move the prompt to the bottom of the window but leaves the original help section visible above it, other than that visual change, nothing else seems to change

Thanks, that is definitely not something jj-fzf can fix.

It's probably some interaction between fzf output and your terminal.
Have you tried updating both, also fzf?
If the problem persists we might need to come up with an fzf command line that reproduces your issue and file it as fzf or ghostty bug.

**Comment by niveK77pur** [comment]
Understandable! Yes, maybe we uncovered a little bug in fzf and/or ghostty here. I updated both, but the issue persists. Here are my versions:

```
❯ fzf --version
0.65.1 (v0.65.1)
❯ ghostty --version
Ghostty 1.1.3

Version
  - version: 1.1.3
  - channel: stable
Build Config
  - Zig version: 0.13.0
  - build mode : builtin.OptimizeMode.ReleaseFast
  - app runtime: apprt.Runtime.gtk
  - font engine: font.main.Backend.fontconfig_freetype
  - renderer   : renderer.OpenGL
  - libxev     : main.Backend.io_uring
  - desktop env: other
  - GTK version:
    build      : 4.18.6
    runtime    : 4.18.6
  - libadwaita : enabled
    build      : 1.7.5
    runtime    : 1.7.5
  - libX11     : enabled
  - libwayland : enabled
```

At a glance, I could not find which fzf flags I would use to replicate the kind of help menu that is being displayed, so I couldn't test right away if I can replicate it.
